"use strict";

describe("Commons for project builds", function() {
  const fs = require("fs");
  const path = require("path");

  const utils = require(path.resolve("src/utils/utils"));
  const config = require(path.resolve("src/utils/config"));
  const model = require(path.resolve("src/models/model"));

  const cmns = require(path.resolve(
    "src/" + config.getJobNameForPipeline1() + "/commons"
  ));

  it("should generate a typical Maven build script.", function() {
    // replay
    var script = utils.getScriptAsString(
      cmns.getMavenProjectBuildScript("project_type")
    );

    // verif
    expect(script).toContain("#!/bin/bash\n");
    expect(script).toContain(
      "# Autogenerated script to build projects of type 'project_type'...\n"
    );
    expect(script).toContain("mvn clean install\n");
  });

  it("should generate a typical Maven deploy script.", function() {
    // replay
    var script = utils.getScriptAsString(
      cmns.getMavenProjectDeployScript("project_type", "URL_ENVVAR_NAME")
    );

    // verif
    expect(script).toContain("#!/bin/bash\n");
    expect(script).toContain(
      "# Autogenerated script to deploy projects of type 'project_type'...\n"
    );
    expect(script).toContain("nexus_envvars=$1 ; . $nexus_envvars\n");
    expect(script).toContain(
      "mvn clean deploy -DskipTests -DaltDeploymentRepository=${NEXUS_REPO_ID}::default::${URL_ENVVAR_NAME}\n"
    );
  });

  it("should generate an 'Artifact' for a Maven project.", function() {
    // setup
    const projectType = "openmrsmodule";

    // replay
    var artifact = cmns.getMavenProjectArtifact(
      path.resolve(
        "spec/" + config.getJobNameForPipeline1() + "/resources/" + projectType
      ),
      "./target",
      "omod"
    );

    // verif
    expect(artifact instanceof model.Artifact).toBeTruthy();
    expect(artifact.name).toEqual("exti18n");
    expect(artifact.version).toEqual("1.1.0-SNAPSHOT");
    expect(artifact.buildPath).toEqual("./target");
    expect(artifact.filename).toEqual("exti18n-1.1.0-SNAPSHOT.omod");
    expect(artifact.extension).toEqual("omod");
    expect(artifact.destFilename).toEqual(artifact.filename);

    expect(artifact.mavenProject instanceof model.MavenProject).toBeTruthy();
    expect(artifact.mavenProject.groupId).toEqual("org.openmrs.module");
    expect(artifact.mavenProject.artifactId).toEqual(artifact.name);
    expect(artifact.mavenProject.version).toEqual(artifact.version);
    expect(artifact.mavenProject.packaging).toEqual(artifact.extension);
  });
});
