"use strict";

/**
 * @param {string} process.env.instanceDefinitionEvent - Parts of an instance definition that have changed.
 * A entire instance definition is also a possible input.
 */

const fs = require("fs");
const path = require("path");
const _ = require("lodash");

const utils = require("../utils/utils");
const model = require("../models/model");
const cst = require("../const");
const config = require(cst.CONFIGPATH);
const db = require(cst.DBPATH);

//
//  Fetching the instance definition based on the provided UUID
//
var instanceDef = db.getInstanceDefinition(
  process.env[config.varInstanceUuid()]
);
if (_.isEmpty(instanceDef)) {
  throw new Error();
}

//
//  Building the pre-host connecton CD preparation script
//
var script = new model.Script();
script.type = "#!/bin/bash";
script.headComment =
  "# Autogenerated script for the CD instance preparation prior to connecting to the host...";
script.body = "";

if (process.env[config.varArtifactsChanges()] === "true") {
  script.body += require("./impl/fetch").getFetchArtifactsScript(
    instanceDef.artifacts,
    config.getCDArtifactsDirPath(instanceDef.uuid)
  );
}
if (process.env[config.varDataChanges()] === "true") {
  // TODO
}

//
//  Saving the script in the current build dir.
//
fs.writeFileSync(
  path.resolve(config.getBuildDirPath(), config.getPrehostPrepareScriptName()),
  utils.getScriptAsString(script)
);
fs.chmodSync(
  path.resolve(config.getBuildDirPath(), config.getPrehostPrepareScriptName()),
  "0755"
);
