"use strict";

/**
 * @param {string} process.env.instanceDefinitionEvent - Parts of an instance definition that have changed.
 * A entire instance definition is also a possible input.
 */

const fs = require("fs");
const path = require("path");

const utils = require(path.resolve("src/utils/utils"));
const model = require(path.resolve("src/models/model"));
const config = require("../utils/config");

//
//  Fetching the instance definition based on the provided UUID
//
var instances = JSON.parse(
  fs.readFileSync(config.getInstancesConfigPath(), "utf8")
);
var instanceDef = utils.findInstanceInList(
  process.env[config.varInstanceUuid()],
  null,
  instances
);

//
//  Building the pre-host connecton CD preparation script
//
var script = new model.Script();
script.type = "#!/bin/bash";
script.headComment =
  "# Autogenerated script for the CD instance preparation prior to connecting to the host...";
script.body = "";

if (process.env[config.varArtifactsChanges()] === "true") {
  script.body += require("./impl/fetch").getFetchArtifactsScript(
    instanceDef.artifacts,
    config.getCDArtifactsDirPath(instanceDef.uuid)
  );
}
if (process.env[config.varDataChanges()] === "true") {
  // TODO
}

//
//  Saving the script in the current build dir.
//
fs.writeFileSync(
  path.resolve(config.getBuildDirPath(), config.getPrehostPrepareScriptName()),
  utils.getScriptAsString(script)
);
fs.chmodSync(
  path.resolve(config.getBuildDirPath(), config.getPrehostPrepareScriptName()),
  "0755"
);
