var model = require('../model')
var utils = require('../../utils/utils')
var fs = require('fs')

module.exports = {

  getInstance: function() {

    var project = new model.Project();

    // Implement here the Project object methods
    project.getBuildScriptAsString = function () {
      return getBuildScriptAsString();
    }
    project.getBuildScript = function () {
      return getBuildScript();
    }
    project.getArtifact = function () {
      var artifact = new model.Artifact();

      artifact.extension = "zip"
      artifact.path = "./ui/target"

      // Version is not managed through npm or maven project
      artifact.version = ""
      artifact.name = "bahmniapps"

      artifact.filename = artifact.name + "." + artifact.extension

      return artifact
    }

    return project
  } 
}

var getBuildScript = function() {

  var buildScript = new model.BuildScript();

  buildScript.type = "#!/bin/bash"
  buildScript.comments = "# Autogenerated script to build 'bahmniapps' type of projects"
  buildScript.value = "cd ./ui\n"
  buildScript.value = buildScript.value + "./scripts/package.sh\n"

  return buildScript    
}

var getBuildScriptAsString = function() {

  var buildScript = getBuildScript()

  var string = ""

  string = buildScript.type
  string = string + "\n\n"
  string = string + buildScript.comments
  string = string + "\n\n"
  string = string + buildScript.value

  return string
}

