version: 1

build:
  bash_commands: "mvn clean test -P IT"
deploy:
  bash_commands: "mvn clean deploy -DskipTests -DaltDeploymentRepository=mks-nexus::default::https://nexus.mekomsolutions.net/repository/maven-snapshots"
  artifact:
    groupId: "org.openmrs"
    artifactId: "dbsync"
    version: "dev"
