"use strict";

const fs = require("fs");
const path = require("path");
const _ = require("lodash");
const log = require("npmlog");

const model = require(path.resolve("src/models/model"));
const utils = require(path.resolve("src/utils/utils"));

module.exports = {
  getInstance: function() {
    var projectBuild = new model.ProjectBuild();

    projectBuild.getBuildScript = function() {
      return getBuildScript();
    };

    projectBuild.getArtifact = function(pomPath, commitMetadata) {
      return getArtifact(pomPath, commitMetadata);
    };

    projectBuild.getDeployScript = function(project) {
      return getDeployScript(project);
    };

    return projectBuild;
  }
};

var getArtifact = function(pomPath, commitMetadata) {
  if (_.isUndefined(commitMetadata) || _.isEmpty(commitMetadata)) {
    log.error(
      "",
      "No commit metadata was passed to Bahmni Apps' getArtifact(..)."
    );
    process.exit(1);
  }

  var artifact = new model.Artifact();
  artifact.name = "bahmniapps";
  // Bahmni Apps is not version-managed, we infer its version from either the branch name or commit ID.
  if (commitMetadata.branchName) {
    artifact.version = commitMetadata.branchName;
  } else {
    artifact.version = commitMetadata.commitId;
  }
  artifact.buildPath = "./ui/target";
  artifact.extension = "zip";
  artifact.filename = artifact.name + "." + artifact.extension;
  artifact.destFilename =
    artifact.name + "-" + artifact.version + "." + artifact.extension;

  // encapsulating the Maven project
  {
    var mavenProject = new model.MavenProject();
    mavenProject.groupId = "net.mekomsolutions";
    mavenProject.artifactId = artifact.name;
    mavenProject.version = artifact.version;
    artifact.mavenProject = mavenProject;
  }

  return artifact;
};

var getBuildScript = function() {
  var buildScript = new model.Script();

  buildScript.type = "#!/bin/bash";
  buildScript.headComment =
    "# Autogenerated script to build 'bahmniapps' type of projects";

  buildScript.body = "cd ./ui\n";
  buildScript.body += "./scripts/package.sh\n";

  return buildScript;
};

var getDeployScript = function(artifact) {
  var deployScript = new model.Script();
  if (_.isUndefined(artifact)) {
    log.error(
      "",
      "An artifact parameter must be provided to construct the Bahmni Apps deploy script."
    );
    throw new Error();
  }
  deployScript.type = "#!/bin/bash";
  deployScript.headComment =
    "# Autogenerated script to deploy 'bahmniapps' type of projects";

  deployScript.body = "nexus_envvars=$1 ; . $nexus_envvars\n";
  deployScript.body +=
    "mvn deploy:deploy-file -DgroupId=net.mekomsolutions -DartifactId=" +
    artifact.name +
    " -Dversion=" +
    artifact.version +
    " -Dpackaging=" +
    artifact.extension +
    " -DrepositoryId=${NEXUS_REPO_ID} -Durl=${ARTIFACT_UPLOAD_URL_bahmniapps} -Dfile=" +
    artifact.destFilename +
    "\n";

  return deployScript;
};
