var model = require("../../models/model");
var utils = require("../../utils/utils");
var fs = require("fs");

module.exports = {
  getInstance: function() {
    var projectBuild = new model.ProjectBuild();

    // Implement here the ProjectBuild object methods
    projectBuild.getBuildScript = function() {
      return getBuildScript();
    };
    projectBuild.getArtifact = function(pomPath) {
      var pom = utils.getPom(pomPath);
      var project = new model.ProjectBuild();
      project.version = pom.version;
      project.name = pom.artifactId;
      project.module = "webapp";
      project.groupId = pom.groupId;

      var artifact = new model.Artifact();

      artifact.extension = "omod";
      artifact.path = "./omod/target";
      artifact.filename =
        project.name + "-" + project.version + "." + artifact.extension;
      artifact.destFilename = artifact.filename;

      artifact.project = project;

      return artifact;
    };
    projectBuild.getDeployScript = function() {
      return getDeployScript();
    };
    projectBuild.getDeployScript = function() {
      return getDeployScript();
    };

    return projectBuild;
  }
};

var getBuildScript = function() {
  var buildScript = new model.Script();

  buildScript.type = "#!/bin/bash";
  buildScript.comments =
    "# Autogenerated script to build 'openmrscore' type of projects";
  buildScript.value = "mvn clean install\n";

  return buildScript;
};

var getDeployScript = function() {
  var deployScript = new model.Script();

  deployScript.type = "#!/bin/bash";
  deployScript.comments =
    "# Autogenerated script to deploy 'openmrscore' type of projects";
  deployScript.value = "nexus_envvars=$1 ; . $nexus_envvars\n";
  deployScript.value =
    deployScript.value +
    "mvn clean deploy -DskipTests -DaltDeploymentRepository=${NEXUS_REPO_ID}::default::${ARTIFACT_UPLOAD_URL_openmrscore}\n";

  return deployScript;
};
