var model = require('./model')
var utils = require('../utils/utils')

module.exports = {

  getInstance: function() {

    var openmrsModule = new model.Project();

    // Implement here the Project object methods
    openmrsModule.getBuildScriptAsString = function () {
      return getBuildScriptAsString();
    }
    openmrsModule.getBuildScript = function () {
      return getBuildScript();
    }
    openmrsModule.getArtifact = function () {
      var name = "lfhcforms"
      return new model.Artifact("./omod/target", name + "-*" + ".omod")
    }

    return openmrsModule
  } 
}

var getBuildScript = function() {

  var buildScript = new model.BuildScript();

  buildScript.type = "#!/bin/bash"
  buildScript.comments = "# Autogenerated script to build 'openmrsmodule' type of projects"
  buildScript.value = "mvn clean install\n"

  return buildScript    
}

var getBuildScriptAsString = function() {

  var buildScript = getBuildScript()

  var string = ""

  string = buildScript.type
  string = string + "\n\n"
  string = string + buildScript.comments
  string = string + "\n\n"
  string = string + buildScript.value

  return string
}
