"use strict";

const path = require("path");
const fs = require("fs");
const log = require("npmlog");
const _ = require("lodash");

const model = require("../utils/model");
const utils = require("../utils/utils");
const cst = require("../const");
const config = require(cst.CONFIGPATH);
const db = require(cst.DBPATH);

module.exports = {
  /*
   * Generates the default build script for Maven projects.
   *
   *  'mvn clean install'
   */
  getMavenProjectBuildScript: function(projectType, profile) {
    var script = new model.Script();

    script.type = "#!/bin/bash";
    script.headComment =
      "# Autogenerated script to build projects of type '" +
      projectType +
      "'...";

    script.body =
      "mvn clean install" +
      (typeof profile === "undefined" ? "" : " -P " + profile) +
      "\n";

    return script;
  },

  /*
   * Generates the default deploy script for Maven projects.
   *
   * @param {string} projectType - Eg. 'openmrsmodule', 'openmrscore', ... etc.
   * @param {string} uploadUrlEnvvarName - Eg. 'ARTIFACT_UPLOAD_URL_openmrsmodule', 'ARTIFACT_UPLOAD_URL_openmrscore', ... etc.
   *
   *  'mvn clean deploy'
   */
  getMavenProjectDeployScript: function(
    projectType,
    uploadUrlEnvvarName,
    profile
  ) {
    var script = new model.Script();

    script.type = "#!/bin/bash";
    script.headComment =
      "# Autogenerated script to deploy projects of type '" +
      projectType +
      "'...";

    script.body = "nexus_envvars=$1 ; . $nexus_envvars\n";
    script.body +=
      "mvn clean deploy -DskipTests" +
      (typeof profile === "undefined" ? "" : " -P " + profile);
    script.body += " ";
    script.body +=
      "-DaltDeploymentRepository=${NEXUS_REPO_ID}::default::${" +
      uploadUrlEnvvarName +
      "}\n";

    return script;
  },

  /*
   * Generates a default 'Artifact' object for a Maven project.
   *  The ouput encapsulates the 'MavenProject' object.
   *
   * @param {Object} pom - A JSON representation of the POM XML.
   * @param {String} buildPath - The relative build path. Eg. './target'
   * @param {String} artifactExtension - The extension of the build output artifact file. Eg. 'omod', 'zip', 'jar'... etc.
   *
   */
  getMavenProjectArtifact: function(pom, buildPath, artifactExtension) {
    var artifact = new model.Artifact();
    artifact.name = pom.artifactId;
    artifact.version = pom.version;
    artifact.buildPath = buildPath;
    artifact.extension = artifactExtension;
    artifact.filename =
      artifact.name + "-" + artifact.version + "." + artifact.extension;
    artifact.destFilename = artifact.filename;

    // encapsulating the Maven project
    var mavenProject = new model.MavenProject();
    mavenProject.groupId = pom.groupId;
    mavenProject.artifactId = pom.artifactId;
    mavenProject.version = pom.version;
    mavenProject.packaging = artifactExtension;
    artifact.mavenProject = mavenProject;

    return artifact;
  },

  /*
   * Looks for projects (typically distributions) impacted by a change in the currently built artifact.
   * Then saves the build parameters of the impacted projects to rebuild them as downstream jobs.
   *
   * @param {String} groupId - The Maven group ID of the currently built project.
   * @param {Array} artifactsIds - All the artifacts IDs (itself and submodules) that belong to the currently built project.
   * @param {String} artifactExtension - The Maven version of the currently built project.
   *
   */
  mavenPostBuildActions: function(groupId, artifactsIds, version) {
    var impactedArtifacts = [];

    // Looking for all artifacts that depend on those of the current project
    var allDeps = db.getAllArtifactDependencies();
    artifactsIds.forEach(function(artifactId) {
      var artifactKey = utils.toArtifactKey(groupId, artifactId, version);
      allDeps.forEach(function(deps) {
        if (deps.dependencies.indexOf(artifactKey) > -1) {
          impactedArtifacts.push(deps.artifactKey);
        }
      });
    });
    impactedArtifacts = _.uniq(impactedArtifacts);

    // Fetching the build parameters of the impacted artifacts (typically distributions)
    var params = [];
    impactedArtifacts.forEach(function(artifactKey) {
      var buildParams = db.getArtifactBuildParams(artifactKey);
      params.push(buildParams["buildParams"]);
    });
    fs.writeFileSync(
      // saving them to a file specific to the current build
      config.getDownstreamBuildParamsJsonPath(),
      JSON.stringify(params)
    );
  },

  getMavenArtifactIds: function(artifactsIdsFilePath) {
    var artifactsIds = [];
    try {
      // artifacts IDs of all the Maven (sub)modules found, so one per POM found
      // there won't be anything gathered here for POM-less projects (eg. Bahmni Apps... etc)
      artifactsIds = fs
        .readFileSync(artifactsIdsFilePath, "utf-8")
        .toString()
        .split("\n");

      artifactsIds = artifactsIds.filter(Boolean);
    } catch (err) {
      log.warn(
        "",
        "No artifacts IDs were extracted out of the POM files, is this not a Maven project?"
      );
      log.warn("", JSON.stringify(err, null, 2));
    }
    return artifactsIds;
  },
  /*
   * Generates the default build script for Gradle projects.
   *
   * @param {string} projectType - Eg. 'odooaddon', ... etc.
   *
   *  './gradlew clean install'
   */
  getGradleProjectBuildScript: function(projectType) {
    var script = new model.Script();

    script.type = "#!/bin/bash";
    script.headComment =
      "# Autogenerated script to build projects of type '" +
      projectType +
      "'...";

    script.body = "./gradlew clean install\n";
    return script;
  },

  /*
   * Generates the default deploy script for Maven projects.
   *
   * @param {string} projectType - Eg. 'odooaddon', ... etc.
   * @param {string} uploadUrlEnvvarName - Eg. 'ARTIFACT_UPLOAD_URL_odooaddon', ... etc.
   *
   *  './gradlew publish -P...'
   */
  getGradleProjectDeployScript: function(projectType, uploadUrlEnvvarName) {
    var script = new model.Script();

    script.type = "#!/bin/bash";
    script.headComment =
      "# Autogenerated script to deploy projects of type '" +
      projectType +
      "'...";

    script.body = "nexus_envvars=$1 ; . $nexus_envvars\n";
    script.body += "./gradlew publish";
    script.body += " ";
    script.body += "-PrepoId=${NEXUS_REPO_ID}";
    script.body += " ";
    script.body += "-Purl=${" + uploadUrlEnvvarName + "}\n";

    return script;
  }
};
